config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "orders#index"

  resources :orders, only: [:update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/discount_code.rb
class DiscountCode < ApplicationRecord
	has_many :discount_orders
	has_many :orders, through: :discount_orders
end

app/models/discount_order.rb
class DiscountOrder < ApplicationRecord
	belongs_to :discount_code
	belongs_to :order
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :order
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :items, dependent: :destroy

	has_many :promo_orders
	has_many :promo_codes, through: :promo_orders

	has_many :discount_orders
	has_many :discount_codes, through: :discount_orders

	enum status: [:in_progress, :completed]
end

app/models/promo_code.rb
class PromoCode < ApplicationRecord
	has_many :promo_orders
	has_many :orders, through: :promo_orders
end

app/models/promo_order.rb
class PromoOrder < ApplicationRecord
	belongs_to :promo_code
	belongs_to :order
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_action :get_order, only: [:update]

	def index
		@orders = Order.in_progress.includes(:items)
	end

	def update
		if @order.update(status: Order.statuses['completed'])
			flash[:notice] = 'status has been updated'
		else
			flash[:alert] = 'Error while updating status'
		end
		redirect_to root_path
	end

	private

	def get_order
		@order = Order.find_by(id: params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodingTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<div><b>Orders</b></div>
<hr>

<% @orders.each do |order| %>
	<div class="row">
		<div class="col-md-6">
			ID: <span><%= order.id %></span><br/><br/> 
			Created At: <span><%= order.created_at %></span><br/><br/> 
			Promotion Codes: <span><%= order.promo_codes.pluck(:code).to_sentence %></span><br/><br/> 
			Discount Codes: <span><%= order.discount_codes.pluck(:code).to_sentence %></span><br/><br/>
			<br/><br/> 

			Total Price: <span><%= order.price.to_f %>$</span>
		</div>
		</br>
		<%= button_to 'Completed', order_path(order), { method: :patch, form: { data: { turbo: true } } } %>
		</br>
		</br>
		<div class="col-md-6">
			Items:
			<ul>
				<% order.items.each do |item| %>
					<li><%= item.name %>(<%= item.size %>)
						<% if item.instructions.present? %>
							<li><%= item.instructions %></li>
						<% end %>
					</li><br/><br/>
				<% end %>
			</ul>
		</div>
	</div>
	<hr>
<% end %>